### ISSUE TITLE
Interface des programmes

### ISSUE THREAD

**Issue by RedBullInsomnia** [RedBullInsomnia/Satcamp#10]
- Fixer des tailles minimales pour les programmes (à voir).
- S'arranger pour que l'interface reste plaisante quand on resize la fenêtre.
- Rajouter un bouton de déconnection.

**Comment by waliens** [comment]
La taille et le resize sont vraiment prioritaires?

**Comment by RedBullInsomnia** [comment]
C'est une feature agréable et assez simple à mettre en place. Mais pas prioritaire.

**Comment by waliens** [comment]
Done
