### ISSUE TITLE
Problèmes de connection

### ISSUE THREAD

**Issue by RedBullInsomnia** [RedBullInsomnia/Satcamp#11]
Je ne sais pas ce qu'il est possible de faire. Dans l'état actuel c'est assez pénible d'utiliser le programme car il faut d'abord connecter le satellite à un écran et un clavier pour mettre en place la connection, et récupérer l'adresse ip.

L'idéal serait de connecter la batterie au satellite et que le programme server se lance tout seul et qu'il soit disponible pour un client. Comment le faire, je sais pas trop. Il pourrait créer une connection ad hoc et avoir une ip fixe ? L'utilisateur n'aurait qu'à s'identifier à ce réseau et lancer le programme client qui pourrait alors se connecter à cette ip connue. Si tu as d'autres idées pour résoudre ce problème....

**Comment by waliens** [comment]
C'est peut être réglé : j'ai été fixer l'ip dans le panneau de configuration : 
Panneau de configuration > Réseau et Internet > Centre Réseau et partage > "Wi-Fi 3" > Propriétés > Protocole Internet version 4 (TCP/IPv4) 

J'ai mis : 
- ip : 192.168.1.96
- subnet mask : 255.255.255.0
- default gateway : 192.168.1.1

DNS : 
- ip : 8.8.8.8 (dns de google si je ne m'abuse)

A priori ça marche (je veux dire par là que l'ip 192.168.1.96 peut être utilisée dans le code client), mais ce serait bien de tester plus en profondeur (je vais déjà voir si ça se maintient au re-démarrage.

**Comment by waliens** [comment]
L'ip est bien fixée mais vu que je teste, je n'ai pas encore mis un démarrage auto pour la nouvelle version du serveur. Ce sera chose faite quand le serveur sera fini.

**Comment by RedBullInsomnia** [comment]
D'accord. 

(8.8.8.8 est bien le dns de google ^^ )
