### ISSUE TITLE
Enregistrer image, vidéo

### ISSUE THREAD

**Issue by RedBullInsomnia** [RedBullInsomnia/Satcamp#13]
Pour l'instant, l'image est enregistrée en tant que screenshot grâce à une fonction de c#. Ce serait mieux d'enregistrer juste l'image, comme tu avais réussi à le faire. On avait du l'enlever à cause d'une erreur d'exécution bizarre.

Tant qu'on y est, s'il est possible de prendre des vidéos, c'est bien aussi

**Comment by waliens** [comment]
Seulement image finalement
