### ISSUE TITLE
Possibilité de rentrer un [Pitch, Yaw, Roll] de stabilisation

### ISSUE THREAD

**Issue by RedBullInsomnia** [RedBullInsomnia/Satcamp#2]
Il faudrait rendre possible le renseignement d'un ou deux degrés de contraintes à la main et non uniquement à l'aide de sliders. Donc, rajouter 1 champ à côté de chaque slider

**Comment by waliens** [comment]
Not solved -> l'accéléromètre étant très instable, il est impossible de stabiliser

**Comment by waliens** [comment]
Mais lorsque ce sera réglé, la fonctionnalité est implémentée
