### ISSUE TITLE
Le programme est tellement mal écrit qu'il est impossible de tester les sous modules

### ISSUE THREAD

**Issue by RedBullInsomnia** [RedBullInsomnia/Satcamp#6]
Il faudrait rendre possible le démarrage du programme SANS la caméra/servos. Sinon c'est galère pour développer.

**Comment by RedBullInsomnia** [comment]
Je le ré-ouvre car ca pourait accélérer le dévelopement de le faire -  séparer les modules, pour qu'on puisse lancer le programme sns la camér ou sans le servo, sans se tapper d'erreur.

**Comment by waliens** [comment]
Personnellement, je n'ai pas de problème avec ça pour le développement. Ce qu'il faudrait faire éventuellement, c'est écrire des programmes standalones pour tester les sous modules et garder le programme principal le plus simple et lisible possible

**Comment by RedBullInsomnia** [comment]
Ok, si ca te ne dérange pas... Moi ca me saoulait parce que je montais et démontais le sat en permanence ...
